Sync README and CSV.
f/awesome-chatgpt-prompts pull request #206
Opened 2023-01-02 03:12 UTC by canburak

Address the discrepancies between the `prompts.csv` and `README.md`.

I could have extended the CSV linter workflow and fail the build as needed but until then, here is the helper script I've used for the interested:

```python
import csv
from Levenshtein import distance

readme_prompts = []
with open("README.md") as readme:
    prompts_streaming = False
    for line in readme.readlines():
        line = line[:-1]

        if line == "# Prompts":
            prompts_streaming = True
        if line == "# License":
            prompts_streaming = False

        if prompts_streaming and line.startswith(">"):
            line = line.replace("> ", ">")
            readme_prompts.append(line[1:])
        
csv_prompts = []
with open('prompts.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        csv_prompts.append(row["prompt"])

for i, csv_prompt in enumerate(csv_prompts):
    readme_prompt = readme_prompts[i]
    dist = distance(csv_prompt, readme_prompt)
    if dist > 0:
        print(f"{dist}\n\t   CSV: {repr(csv_prompt[:64])}\n\tREADME: {repr(readme_prompt[:64])}")
```

2023-01-09 21:38 UTC, f requested changes

2023-01-09 21:38 UTC, f commented on README.md
> -## Act as a Midjourney Prompt Generator
Why these are deleted. They should be in CSV as well.

2023-01-16 13:40 UTC, canburak commented
Looks like #261 did what I wanted to do in the first place, so maybe check that.

2023-01-16 14:16 UTC, canburak commented
I am pulling this PR back since the repo is being updated frequently, making it impractical for me to keep up.

2023-01-16 14:16 UTC, closed without merging