Added a ChatGPT 3.5 Jailbreak I Have Created
f/awesome-chatgpt-prompts pull request #748
Opened 2024-05-25 17:18 UTC by MarkCyber

This is a chatgpt jailbreak for chatgpt 3.5 I have created that utilizes multiple steps. This jailbreak utilizes hexadecimal to bypass restrictions and allow chatgpt to write malware / hacking scripts that it would not normally do.

Proof of concept: 
<img width="1045" alt="ProofOfConcept" src="https://github.com/f/awesome-chatgpt-prompts/assets/148797232/0e86dce2-2077-4abf-87ac-088c79b14882">

- [yes ] I've confirmed the prompt works well
- [yes ] I've added `Contributed by: [@yourusername](https://github.com/yourusername)`
- [yes ] I've added to the README.md
- [yes ] I've added to the `prompts.csv`
- [yes ] Escaped quotes by double-quoting them
- [yes ] No spaces after commas after double quotes. e.g. `"Hello","hi"`, not `"Hello", "hi"`
- [yes ] Removed "Act as" from the title on CSV

Please make sure you've completed all the checklist.

2024-05-25 17:58 UTC, lozanopo approved these changes

2024-05-25 19:55 UTC, MarkCyber commented
What is the process to have this merged after getting it approved? Is there anything else I need to do on my end?

2024-05-30 06:13 UTC, lozanopo approved these changes

2024-05-30 06:14 UTC, lozanopo approved these changes

2024-05-30 11:04 UTC, davidsneighbour requested changes

2024-05-30 11:04 UTC, davidsneighbour commented on README.md
> -<p align="center"><h1>🧠 Awesome ChatGPT Prompts</h1></p>
Deleting these lines, down to line 97 is not connected to your prompt.

2024-05-30 11:04 UTC, davidsneighbour commented on README.md
> ----
I doubt that intention is a factor in allowing coarse language in a public document. There is a button "collapsible content" in the editor that adds some Github-compatible markdown to collapse text which you might want to use for that?

2024-05-30 17:16 UTC, MarkCyber commented
Okay, I did not do this intentionally. I will fix this now. Thank you for letting me know!

2024-05-30 17:22 UTC, closed without merging

2024-05-30 17:25 UTC, MarkCyber commented
Started a new pull request with all of these changes fixed